// Poker
#define DIALOG_CGAMESADMINMENU      		4090
#define DIALOG_CGAMESSELECTPOKER    		4100
#define DIALOG_CGAMESSETUPPOKER     		4110
#define DIALOG_CGAMESCREDITS        		4120
#define DIALOG_CGAMESSETUPPGAME     		4130
#define DIALOG_CGAMESSETUPPGAME2			4140
#define DIALOG_CGAMESSETUPPGAME3			4150
#define DIALOG_CGAMESSETUPPGAME4			4160
#define DIALOG_CGAMESSETUPPGAME5			4170
#define DIALOG_CGAMESSETUPPGAME6			4180
#define DIALOG_CGAMESSETUPPGAME7			4190
#define DIALOG_CGAMESBUYINPOKER				4200
#define DIALOG_CGAMESCALLPOKER				4210
#define DIALOG_CGAMESRAISEPOKER     		4220
#define OBJ_POKER_TABLE 					19474
#define GUI_POKER_TABLE						0
#define MAX_POKERTABLES 					100
#define MAX_POKERTABLEMISCOBJS				6
#define MAX_PLAYERPOKERUI					48
#define DRAWDISTANCE_POKER_TABLE 			150.0
#define DRAWDISTANCE_POKER_MISC 			50.0
#define CAMERA_POKER_INTERPOLATE_SPEED		5000 // ms (longer = slower)
#define DIALOG_BUYPOKER 					10042

// Hospital dialog
#define DIALOG_HOSPITAL_BILL                9070                   

// Crate System
#define MAX_CRATES 100

// Plant Pot System
#define MAX_PLANTPOT 100

// Dynamic Public Garage
#define MAX_PUBLICGARAGE 50

// Paintball System
#define MAX_PAINTBALL 50

// Local Buyer System
#define MAX_LOCAL_BUYER 100

// Auction
#define MAX_AUCTIONS 10

// Dynamic Tollgate
#define MAX_TOLLGATES 1000

// Dynamic Rent Vehicle
#define MAX_RENT_VEHICLE 100

// Street Vendors
#define	MAX_VENDOR 100

// Dynamic Actor - Tokyo
#define MAX_DYNAMIC_ACTORS      1000

// ATM
#define	MAX_ATM 100

// Deliver PT
#define MAX_DELIVERPT 50

// Arrest Point
#define MAX_ARREST 50

// Dynamic Label
#define MAX_CDYNAMIC_LABEL 100

// Fuel Station
#define MAX_FUEL_STATION                   1500

// Dynamic Faction Vehicle Spawner
#define MAX_FACTION_GARAGE         	1000
#define MAX_FACTION_VEHICLE  		1000

#define MAX_INVENTORY 20

// Plant Pot System
#define MAX_PLANTPOT 100

// Dynamic Public Garage
#define MAX_PUBLICGARAGE 50

// Paintball System
#define MAX_PAINTBALL 50

// Local Buyer System
#define MAX_LOCAL_BUYER 100

// Auction
#define MAX_AUCTIONS 10

// Dynamic Tollgate
#define MAX_TOLLGATES 1000

// Dynamic Rent Vehicle
#define MAX_RENT_VEHICLE 100

// Street Vendors
#define	MAX_VENDOR 100

// Dynamic Actor - Tokyo
#define MAX_DYNAMIC_ACTORS      1000

// ATM
#define	MAX_ATM 100

// Deliver PT
#define MAX_DELIVERPT 50

// Arrest Point
#define MAX_ARREST 50

// Dynamic Label
#define MAX_CDYNAMIC_LABEL 100

// Fuel Station
#define MAX_FUEL_STATION                   1500

// Dynamic Faction Vehicle Spawner
#define MAX_FACTION_GARAGE         	1000
#define MAX_FACTION_VEHICLE  		1000

#define MAX_INVENTORY 20