// --- Server Information --- //
#define SERVER_DEVELOPER "JOMA"
#define SERVER_BOT       "QCRP"
#define VERSION          "v2.0"
#define REVISION         "QC:RP " VERSION
#define SERVER_NAME      "Quezon City Roleplay: Reborn"
#define SERVER_UPDATE    ""
#define SERVER_DIALOG    "{EC7063}"SERVER_NAME" "WHITE""VERSION""
#define SERVER_URL       ""
#define SERVER_MAPNAME 	 "Los Santos"
#define SERVER_LANG		 "Filipino / English"
#define SERVER_ANTICHEAT "SECURITY"