/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

// Disable specific warnings
#pragma warning disable 35
#pragma warning disable 201
#pragma warning disable 229
#pragma warning disable 204  // unused variable
#pragma warning disable 240
#pragma warning disable 252
#pragma warning disable 234
#pragma warning disable 239  // literal array/string passed to a non-const parameter
#pragma warning disable 214  // possibly a "const" array argument was intended
#pragma warning disable 225  // unreachable code
#pragma warning disable 218  // old style prototypes used with optional semicolumns
#pragma warning disable 215  // expression has no effect
#pragma warning disable 203  // symbol is never used
#pragma warning disable 207  // unknown pragma
#pragma warning disable 213  // tag mismatch
#pragma warning disable 202  // number of arguments does not match definition
#pragma warning disable 235  // public function lacks forward declaration

#include <a_samp>
#include <audio-plugin>

// Key press macros
#define PRESSED(%0) (((newkeys & (%0)) == (%0)) && ((oldkeys & (%0)) != (%0)))
#define RELEASED(%0) (((newkeys & (%0)) != (%0)) && ((oldkeys & (%0)) == (%0)))

// ============================================
// FISHING CONFIG - Adjust these values
// ============================================

// Edge Boundaries
#define EDGE_RIGHT      410.0
#define EDGE_LEFT       210.0

// Panic Centers (where fish panics near edges)
#define PANIC_CENTER_RIGHT  380.0
#define PANIC_CENTER_LEFT   220.0

// Panic Mode Range (distance from edge center)
#define PANIC_RANGE     20.0

// Center Zone (for fake escape behavior)
#define CENTER_MIN      300.0
#define CENTER_MAX      340.0

// Catch Box Settings
#define CATCH_BOX_WIDTH         28.0
#define CATCH_BOX_SPEED         2.5
#define CATCH_BOX_MIN           240.0
#define CATCH_BOX_MAX           400.0

// Fish AI States
#define FISH_STATE_SEEKING_EDGE     0
#define FISH_STATE_PANIC_AT_EDGE    1
#define FISH_STATE_FAKE_ESCAPE      2
#define FISH_STATE_RETURN_TO_EDGE   3

// Fishing Wait State Config
#define MIN_WAIT_TIME       3000    // 3 seconds minimum wait
#define MAX_WAIT_TIME       15000   // 15 seconds maximum wait
#define WAIT_CHECK_INTERVAL 500     // Check every 500ms for bite

// Fish Type Speed (Edge Seeking)
#define FISH_SPEED_SMALL    1.4
#define FISH_SPEED_MEDIUM   1.5
#define FISH_SPEED_BIG      1.6

// Panic Mode Speed (At Edges)
#define PANIC_SPEED_SMALL   0.8
#define PANIC_SPEED_MEDIUM  0.8
#define PANIC_SPEED_BIG     0.8

// Fake Escape Speed (slower, hesitant movement)
#define FAKE_ESCAPE_SPEED_SMALL     0.6
#define FAKE_ESCAPE_SPEED_MEDIUM    0.8
#define FAKE_ESCAPE_SPEED_BIG       1.0

// Panic Mode Duration (in ticks, 1 tick = 10ms)
#define PANIC_DURATION_SMALL_MIN    30
#define PANIC_DURATION_SMALL_MAX    80
#define PANIC_DURATION_MEDIUM_MIN   25
#define PANIC_DURATION_MEDIUM_MAX   70
#define PANIC_DURATION_BIG_MIN      20
#define PANIC_DURATION_BIG_MAX      60

// Panic Mode Direction Change Chance (0-100%)
#define PANIC_DIRECTION_CHANGE_CHANCE   5

// Fake Escape Behavior Chance (0-100%)
// Higher = more likely to fake escape instead of going to opposite edge
#define FAKE_ESCAPE_CHANCE_SMALL    70
#define FAKE_ESCAPE_CHANCE_MEDIUM   75
#define FAKE_ESCAPE_CHANCE_BIG      80

// Number of fake escapes before real edge switch
#define FAKE_ESCAPE_COUNT_MIN       1
#define FAKE_ESCAPE_COUNT_MAX       3

// ============================================
// END CONFIG
// ============================================

new PlayerText:PlayerTD[MAX_PLAYERS][10];
new PlayerText:border[MAX_PLAYERS];
new PlayerText:container[MAX_PLAYERS];
new PlayerText:catch_box[MAX_PLAYERS];
new PlayerText:fish_sprite[MAX_PLAYERS];
new PlayerText:reel_bubble[MAX_PLAYERS];

new bool:FishingUI[MAX_PLAYERS];
new Float:FishX[MAX_PLAYERS];
new FishDir[MAX_PLAYERS]; // 1 = right, -1 = left
new FishTimer[MAX_PLAYERS];
new FishType[MAX_PLAYERS];
new FishPauseCounter[MAX_PLAYERS];
new Float:FishCurrentSpeed[MAX_PLAYERS];

// Wait State System
new bool:FishingWaitState[MAX_PLAYERS];
new bool:FishingStarting[MAX_PLAYERS]; // Track if player is in fishing start animation
new FishingWaitTimer[MAX_PLAYERS];
new FishingWaitStartTime[MAX_PLAYERS];
new FishingBiteTime[MAX_PLAYERS];
new PlayerFishingLevel[MAX_PLAYERS];

// AI State System
new FishState[MAX_PLAYERS];
new FishStateCounter[MAX_PLAYERS];
new Float:FishPanicCenter[MAX_PLAYERS];
new FishTargetEdge[MAX_PLAYERS]; // 1 = right, -1 = left
new FishFakeEscapeCount[MAX_PLAYERS];
new FishFakeEscapesRemaining[MAX_PLAYERS];

// Catch Box Movement
new Float:CatchBoxX[MAX_PLAYERS];
new Float:CatchBoxSpeed[MAX_PLAYERS];
new CatchBoxMoving[MAX_PLAYERS]; // -1 = left, 0 = stopped, 1 = right

// Miss Counter System
new PlayerFishingMissCount[MAX_PLAYERS];

// Audio Handle System
new FishingAudioHandle[MAX_PLAYERS];

// Battle Sound System
new LastBattleIntensity[MAX_PLAYERS];

#define MAX_FISHING_MISSES 3

#define FISH_SMALL 1
#define FISH_MEDIUM 2
#define FISH_BIG 3

// Audio IDs for fishing sounds
#define AUDIO_FISHING_THEME 1

public OnFilterScriptInit()
{
	printf("[FISHING TXD] Fishing UI system initialized.");
	return 1;
}

public OnFilterScriptExit()
{
	return 1;
}

public OnPlayerConnect(playerid)
{
	FishX[playerid] = 311.0;
    FishDir[playerid] = 1;
	
	// Initialize wait state variables
	FishingWaitState[playerid] = false;
	FishingStarting[playerid] = false;
	FishingWaitTimer[playerid] = 0;
	PlayerFishingLevel[playerid] = 0;
	PlayerFishingMissCount[playerid] = 0;

	border[playerid] = CreatePlayerTextDraw(playerid, 320.000000, 341.000000, "_");
	PlayerTextDrawFont(playerid, border[playerid], 1);
	PlayerTextDrawLetterSize(playerid, border[playerid], 0.600000, 3.149980);
	PlayerTextDrawTextSize(playerid, border[playerid], 298.500000, 230.000000);
	PlayerTextDrawSetOutline(playerid, border[playerid], 1);
	PlayerTextDrawSetShadow(playerid, border[playerid], 0);
	PlayerTextDrawAlignment(playerid, border[playerid], 2);
	PlayerTextDrawColor(playerid, border[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, border[playerid], 255);
	PlayerTextDrawBoxColor(playerid, border[playerid], -1);
	PlayerTextDrawUseBox(playerid, border[playerid], 1);
	PlayerTextDrawSetProportional(playerid, border[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, border[playerid], 0);

	container[playerid] = CreatePlayerTextDraw(playerid, 320.000000, 344.000000, "_");
	PlayerTextDrawFont(playerid, container[playerid], 1);
	PlayerTextDrawLetterSize(playerid, container[playerid], 1.016666, 2.449996);
	PlayerTextDrawTextSize(playerid, container[playerid], 291.500000, 224.500000);
	PlayerTextDrawSetOutline(playerid, container[playerid], 1);
	PlayerTextDrawSetShadow(playerid, container[playerid], 0);
	PlayerTextDrawAlignment(playerid, container[playerid], 2);
	PlayerTextDrawColor(playerid, container[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, container[playerid], 255);
	PlayerTextDrawBoxColor(playerid, container[playerid], 678021375);
	PlayerTextDrawUseBox(playerid, container[playerid], 1);
	PlayerTextDrawSetProportional(playerid, container[playerid], 0);
	PlayerTextDrawSetSelectable(playerid, container[playerid], 0);

	catch_box[playerid] = CreatePlayerTextDraw(playerid, 319.000000, 344.000000, "_");
	PlayerTextDrawFont(playerid, catch_box[playerid], 1);
	PlayerTextDrawLetterSize(playerid, catch_box[playerid], 0.600000, 2.449999);
	PlayerTextDrawTextSize(playerid, catch_box[playerid], 298.500000, 28.000000);
	PlayerTextDrawSetOutline(playerid, catch_box[playerid], 1);
	PlayerTextDrawSetShadow(playerid, catch_box[playerid], 0);
	PlayerTextDrawAlignment(playerid, catch_box[playerid], 2);
	PlayerTextDrawColor(playerid, catch_box[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, catch_box[playerid], 16711935);
	PlayerTextDrawBoxColor(playerid, catch_box[playerid], 16711935);
	PlayerTextDrawUseBox(playerid, catch_box[playerid], 1);
	PlayerTextDrawSetProportional(playerid, catch_box[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, catch_box[playerid], 0);

	fish_sprite[playerid] = CreatePlayerTextDraw(playerid, 311.000000, 346.000000, "conrrp_fishing:fish_right");
	PlayerTextDrawFont(playerid, fish_sprite[playerid], 4);
	PlayerTextDrawLetterSize(playerid, fish_sprite[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, fish_sprite[playerid], 17.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, fish_sprite[playerid], 1);
	PlayerTextDrawSetShadow(playerid, fish_sprite[playerid], 0);
	PlayerTextDrawAlignment(playerid, fish_sprite[playerid], 1);
	PlayerTextDrawColor(playerid, fish_sprite[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, fish_sprite[playerid], 255);
	PlayerTextDrawBoxColor(playerid, fish_sprite[playerid], 255);
	PlayerTextDrawUseBox(playerid, fish_sprite[playerid], 1);
	PlayerTextDrawSetProportional(playerid, fish_sprite[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, fish_sprite[playerid], 0);

	reel_bubble[playerid] = CreatePlayerTextDraw(playerid, 213.000000, 360.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, reel_bubble[playerid], 4);
	PlayerTextDrawLetterSize(playerid, reel_bubble[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, reel_bubble[playerid], -4.000000, 5.000000);
	PlayerTextDrawSetOutline(playerid, reel_bubble[playerid], 1);
	PlayerTextDrawSetShadow(playerid, reel_bubble[playerid], 0);
	PlayerTextDrawAlignment(playerid, reel_bubble[playerid], 1);
	PlayerTextDrawColor(playerid, reel_bubble[playerid], -1061109644);
	PlayerTextDrawBackgroundColor(playerid, reel_bubble[playerid], 255);
	PlayerTextDrawBoxColor(playerid, reel_bubble[playerid], 50);
	PlayerTextDrawUseBox(playerid, reel_bubble[playerid], 1);
	PlayerTextDrawSetProportional(playerid, reel_bubble[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, reel_bubble[playerid], 0);

	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 234.000000, 351.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], -5.500000, 7.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1061109661);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 258.000000, 360.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], -4.000000, 5.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1061109661);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 296.000000, 352.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], -5.500000, 7.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1061109661);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 361.000000, 349.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], -4.500000, 4.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1061109661);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 345.000000, 358.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], -5.500000, 7.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1061109661);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 385.000000, 353.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], -5.500000, 7.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1061109661);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 416.000000, 359.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], -4.500000, 4.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1061109661);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 273.000000, 351.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], -1.500000, 3.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1061109644);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 430.000000, 351.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], -1.500000, 3.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1061109644);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 404.000000, 351.000000, "ld_pool:ball");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], -1.500000, 3.500000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1061109644);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
    for(new i = 0; i < 10; i++)
    {
        PlayerTextDrawDestroy(playerid, PlayerTD[playerid][i]);
    }

    PlayerTextDrawDestroy(playerid, border[playerid]);
    PlayerTextDrawDestroy(playerid, container[playerid]);
    PlayerTextDrawDestroy(playerid, catch_box[playerid]);
    PlayerTextDrawDestroy(playerid, fish_sprite[playerid]);
    PlayerTextDrawDestroy(playerid, reel_bubble[playerid]);

	FishingUI[playerid] = false;
	
	// Clean up wait state
	if(FishingWaitTimer[playerid]) KillTimer(FishingWaitTimer[playerid]);
	FishingWaitState[playerid] = false;
	FishingStarting[playerid] = false;

    return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/editrod", true))
	{
		new adminLevel = CallRemoteFunction("GetPlayerAdminLevel", "i", playerid);
		if(adminLevel < 8)
		{
			SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[ERROR]{FFFFFF} Admin level 8+ required");
			return 1;
		}
		EditAttachedObject(playerid, 0);
		return 1;
	}

	if(!strcmp(cmdtext, "/fish", true))
	{
		// Check player state
		new playerState = GetPlayerState(playerid);
		
		// Block if driving any vehicle (including boats)
		if(playerState == PLAYER_STATE_DRIVER)
		{
			SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[FISHING]{FFFFFF} You can't fish while driving!");
			SendClientMessage(playerid, -1, "{FFFFFF}Stand on the boat deck to fish.");
			return 1;
		}
		
		// Check if player is on a fishing boat using helper function
		// This function checks if player is on foot AND on a boat deck
		if(!CallRemoteFunction("IsPlayerOnFishingBoat", "i", playerid))
		{
			SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[FISHING]{FFFFFF} You must be on a fishing boat to fish!");
			SendClientMessage(playerid, -1, "{FFFFFF}Find a {00BFFF}Reefer boat{FFFFFF} in the fishing zone.");
			return 1;
		}
		
		// Check if in fishing zone (call from fishing_rpg_master via CallRemoteFunction)
		new zoneIdx = CallRemoteFunction("GetPlayerZone", "i", playerid);
		
		printf("[FISHING DEBUG] /fish command - playerid: %d, zoneIdx: %d", playerid, zoneIdx);
		
		if(zoneIdx == 0) // 0 means not in any zone (1-based index)
		{
			SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[FISHING]{FFFFFF} You must be in a fishing zone!");
			SendClientMessage(playerid, -1, "{FFFFFF}Use {3498DB}/fishzone list{FFFFFF} to see available zones");
			return 1;
		}
		
		// Check if player has fishing rod
		new rodID = CallRemoteFunction("GetPlayerFishingRodID", "i", playerid);
		if(rodID == 0)
		{
			SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[FISHING]{FFFFFF} You don't have a fishing rod! Visit /fishingshop to buy one.");
			return 1;
		}
		
		// Check if player has bait
		new baitAmount = CallRemoteFunction("GetPlayerFishingBait", "i", playerid);
		if(baitAmount < 1)
		{
			SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[FISHING]{FFFFFF} You don't have any bait! Visit /fishingshop to buy some.");
			return 1;
		}
		
		// Start fishing wait state
		if(FishingWaitState[playerid])
		{
			SendClientMessage(playerid, -1, "{FF0000}You are already fishing!");
			return 1;
		}
		
		// Set fishing state in RPG system
		CallRemoteFunction("SetPlayerFishingState", "ii", playerid, 1);
		
		// Set fishing starting flag immediately
		FishingStarting[playerid] = true;
		
		// Attach fishing rod and play animation
		SetPlayerAttachedObject(playerid, 0, 18632, 6, 0.079999, 0.020999, -0.027000, 179.099578, 0.000000, 0.000000, 1.000000, 1.000000, 1.000000);
		
		// Play Bat_IDLE for 1 second
		ApplyAnimation(playerid, "BASEBALL", "Bat_IDLE", 4.1, 0, 1, 1, 1, 0, 1);
		
		// After 1 second, play Bat_1 animation
		SetTimerEx("PlayFishingCastAnim", 1000, false, "i", playerid);
		
		// Start wait state after both animations (1000ms + 500ms = 1500ms total)
		SetTimerEx("StartFishingWait", 1500, false, "i", playerid);
		return 1;
	}
	
	// Test command to set fishing level
	if(!strcmp(cmdtext, "/setfishlevel", true, 13))
	{
		new adminLevel = CallRemoteFunction("GetPlayerAdminLevel", "i", playerid);
		if(adminLevel < 8)
		{
			SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[ERROR]{FFFFFF} Admin level 8+ required");
			return 1;
		}
		
		new level;
		if(sscanf(cmdtext[14], "d", level))
		{
			SendClientMessage(playerid, -1, "Usage: /setfishlevel [level 1-10]");
			return 1;
		}
		
		if(level < 1 || level > 10)
		{
			SendClientMessage(playerid, -1, "Fishing level must be between 1 and 10");
			return 1;
		}
		
		PlayerFishingLevel[playerid] = level;
		
		new string[128];
		format(string, sizeof(string), "{3498DB}[FISHING]{FFFFFF} Your fishing level has been set to %d", level);
		SendClientMessage(playerid, -1, string);
		return 1;
	}
	
	return 0;
}

// sscanf stub for testing (remove if you have sscanf plugin)
stock sscanf(const data[], const format[], {Float,_}:...)
{
	#pragma unused data, format
	return 0;
}

ShowFishingUI(playerid)
{
	FishingUI[playerid] = true;
	PlayerFishingMissCount[playerid] = 0; // Reset miss counter
	FishX[playerid] = 320.0; // center
	FishPauseCounter[playerid] = 0;

	// Initialize Catch Box
	CatchBoxX[playerid] = 319.0; // center position
	CatchBoxSpeed[playerid] = CATCH_BOX_SPEED;
	CatchBoxMoving[playerid] = 0; // not moving

	// Initialize AI State System
	FishState[playerid] = FISH_STATE_SEEKING_EDGE;
	FishStateCounter[playerid] = 0;
	FishTargetEdge[playerid] = (random(2) == 0) ? 1 : -1; // randomly choose left or right edge
	FishDir[playerid] = FishTargetEdge[playerid];
	FishFakeEscapeCount[playerid] = random(FAKE_ESCAPE_COUNT_MAX - FAKE_ESCAPE_COUNT_MIN + 1) + FAKE_ESCAPE_COUNT_MIN;
	FishFakeEscapesRemaining[playerid] = FishFakeEscapeCount[playerid];

	// Determine FishType based on actual caught fish rarity and weight
	// Get the caught fish data from RPG system
	new fishRarity = CallRemoteFunction("GetCaughtFishRarity", "i", playerid);
	new Float:fishWeight = Float:CallRemoteFunction("GetCaughtFishWeight", "i", playerid);
	new Float:fishMinWeight = Float:CallRemoteFunction("GetCaughtFishMinWeight", "i", playerid);
	new Float:fishMaxWeight = Float:CallRemoteFunction("GetCaughtFishMaxWeight", "i", playerid);
	
	// Calculate weight percentage (0.0 to 1.0)
	new Float:weightPercent = 0.5; // default to middle
	if(fishMaxWeight > fishMinWeight)
	{
		weightPercent = (fishWeight - fishMinWeight) / (fishMaxWeight - fishMinWeight);
	}
	
	// Determine FishType based on rarity and weight
	// RARITY_COMMON (0) + light weight = FISH_SMALL
	// RARITY_UNCOMMON (1) or COMMON with heavy weight = FISH_MEDIUM
	// RARITY_RARE (2) or LEGENDARY (3) = FISH_BIG
	if(fishRarity == 0) // RARITY_COMMON
	{
		FishType[playerid] = (weightPercent > 0.6) ? FISH_MEDIUM : FISH_SMALL;
	}
	else if(fishRarity == 1) // RARITY_UNCOMMON
	{
		FishType[playerid] = (weightPercent > 0.5) ? FISH_BIG : FISH_MEDIUM;
	}
	else // RARITY_RARE or LEGENDARY
	{
		FishType[playerid] = FISH_BIG;
	}

	switch(FishType[playerid])
	{
		case FISH_SMALL: 
		{
			SendClientMessage(playerid, -1, "Small Fish!");
			FishCurrentSpeed[playerid] = FISH_SPEED_SMALL;
		}
		case FISH_MEDIUM: 
		{
			SendClientMessage(playerid, -1, "Medium Fish!");
			FishCurrentSpeed[playerid] = FISH_SPEED_MEDIUM;
		}
		case FISH_BIG: 
		{
			SendClientMessage(playerid, -1, "Big Fish! Hard to catch!");
			FishCurrentSpeed[playerid] = FISH_SPEED_BIG;
		}
	}

	if(FishTimer[playerid]) KillTimer(FishTimer[playerid]);
	FishTimer[playerid] = SetTimerEx("MoveFish", 10, true, "i", playerid);
	
	// Initialize battle sound intensity tracker
	LastBattleIntensity[playerid] = 0;

    for(new i = 0; i < 10; i++)
    {
        PlayerTextDrawShow(playerid, PlayerTD[playerid][i]);
    }

    PlayerTextDrawShow(playerid, border[playerid]);
    PlayerTextDrawShow(playerid, container[playerid]);
    PlayerTextDrawShow(playerid, catch_box[playerid]);
    PlayerTextDrawShow(playerid, fish_sprite[playerid]);
    PlayerTextDrawShow(playerid, reel_bubble[playerid]);
}

HideFishingUI(playerid)
{
	// Clear animation and restore control
	ClearAnimations(playerid);
	if(IsPlayerAttachedObjectSlotUsed(playerid, 0))
	{
		RemovePlayerAttachedObject(playerid, 0);
	}

	FishingUI[playerid] = false;
	
	// Stop fishing theme music
	if(FishingAudioHandle[playerid] != 0)
	{
		Audio_Stop(playerid, FishingAudioHandle[playerid]);
		FishingAudioHandle[playerid] = 0;
		printf("[FISHING AUDIO] Stopped audio for player %d", playerid);
	}

	KillTimer(FishTimer[playerid]);
	FishTimer[playerid] = 0;

    for(new i = 0; i < 10; i++)
    {
        PlayerTextDrawHide(playerid, PlayerTD[playerid][i]);
    }

    PlayerTextDrawHide(playerid, border[playerid]);
    PlayerTextDrawHide(playerid, container[playerid]);
    PlayerTextDrawHide(playerid, catch_box[playerid]);
    PlayerTextDrawHide(playerid, fish_sprite[playerid]);
    PlayerTextDrawHide(playerid, reel_bubble[playerid]);
}

forward MoveFish(playerid);
public MoveFish(playerid)
{
	if(!FishingUI[playerid]) return 1;

	// Check keys using GetPlayerKeys (more reliable for A/D)
	new keys, updown, leftright;
	GetPlayerKeys(playerid, keys, updown, leftright);
	
	// Handle catch box movement with A/D keys
	if(leftright == KEY_LEFT) // A key
	{
		CatchBoxMoving[playerid] = -1; // moving left
	}
	else if(leftright == KEY_RIGHT) // D key
	{
		CatchBoxMoving[playerid] = 1; // moving right
	}
	else
	{
		CatchBoxMoving[playerid] = 0; // stopped
	}

	// Update Catch Box Position (if moving)
	if(CatchBoxMoving[playerid] != 0)
	{
		CatchBoxX[playerid] += CatchBoxMoving[playerid] * CatchBoxSpeed[playerid];
		
		// Clamp to boundaries
		if(CatchBoxX[playerid] < CATCH_BOX_MIN)
		{
			CatchBoxX[playerid] = CATCH_BOX_MIN;
		}
		else if(CatchBoxX[playerid] > CATCH_BOX_MAX)
		{
			CatchBoxX[playerid] = CATCH_BOX_MAX;
		}
		
		// Update catch box textdraw
		PlayerTextDrawHide(playerid, catch_box[playerid]);
		PlayerTextDrawDestroy(playerid, catch_box[playerid]);
		
		catch_box[playerid] = CreatePlayerTextDraw(playerid, CatchBoxX[playerid], 344.000000, "_");
		PlayerTextDrawFont(playerid, catch_box[playerid], 1);
		PlayerTextDrawLetterSize(playerid, catch_box[playerid], 0.600000, 2.449999);
		PlayerTextDrawTextSize(playerid, catch_box[playerid], 298.500000, CATCH_BOX_WIDTH);
		PlayerTextDrawSetOutline(playerid, catch_box[playerid], 1);
		PlayerTextDrawSetShadow(playerid, catch_box[playerid], 0);
		PlayerTextDrawAlignment(playerid, catch_box[playerid], 2);
		PlayerTextDrawColor(playerid, catch_box[playerid], -1);
		PlayerTextDrawBackgroundColor(playerid, catch_box[playerid], 16711935);
		PlayerTextDrawBoxColor(playerid, catch_box[playerid], 16711935);
		PlayerTextDrawUseBox(playerid, catch_box[playerid], 1);
		PlayerTextDrawSetProportional(playerid, catch_box[playerid], 1);
		PlayerTextDrawSetSelectable(playerid, catch_box[playerid], 0);
		
		PlayerTextDrawShow(playerid, catch_box[playerid]);
	}

	// Random pause behavior
	if(FishPauseCounter[playerid] > 0)
	{
		FishPauseCounter[playerid]--;
		return 1;
	}

	// AI STATE MACHINE
	switch(FishState[playerid])
	{
		case FISH_STATE_SEEKING_EDGE:
		{
			// Fish moves toward target edge
			new Float:base_speed;
			switch(FishType[playerid])
			{
				case FISH_SMALL: base_speed = FISH_SPEED_SMALL;
				case FISH_MEDIUM: base_speed = FISH_SPEED_MEDIUM;
				case FISH_BIG: base_speed = FISH_SPEED_BIG;
			}

			// Add slight speed variation
			new Float:speed_multiplier = 0.9 + (random(20) / 100.0);
			FishCurrentSpeed[playerid] = base_speed * speed_multiplier;

			// Move toward target edge
			FishX[playerid] += FishDir[playerid] * FishCurrentSpeed[playerid];

			// Check if reached target edge
			if((FishTargetEdge[playerid] == 1 && FishX[playerid] >= EDGE_RIGHT) || 
			   (FishTargetEdge[playerid] == -1 && FishX[playerid] <= EDGE_LEFT))
			{
				// Clamp to edge
				if(FishTargetEdge[playerid] == 1)
				{
					FishX[playerid] = EDGE_RIGHT;
					FishPanicCenter[playerid] = PANIC_CENTER_RIGHT;
				}
				else
				{
					FishX[playerid] = EDGE_LEFT;
					FishPanicCenter[playerid] = PANIC_CENTER_LEFT;
				}

				// Transition to PANIC state
				FishState[playerid] = FISH_STATE_PANIC_AT_EDGE;
				
				// Set panic duration
				switch(FishType[playerid])
				{
					case FISH_SMALL: FishStateCounter[playerid] = random(PANIC_DURATION_SMALL_MAX - PANIC_DURATION_SMALL_MIN + 1) + PANIC_DURATION_SMALL_MIN;
					case FISH_MEDIUM: FishStateCounter[playerid] = random(PANIC_DURATION_MEDIUM_MAX - PANIC_DURATION_MEDIUM_MIN + 1) + PANIC_DURATION_MEDIUM_MIN;
					case FISH_BIG: FishStateCounter[playerid] = random(PANIC_DURATION_BIG_MAX - PANIC_DURATION_BIG_MIN + 1) + PANIC_DURATION_BIG_MIN;
				}
			}
		}

		case FISH_STATE_PANIC_AT_EDGE:
		{
			FishStateCounter[playerid]--;

			// Erratic movement near edge
			new Float:panic_speed;
			switch(FishType[playerid])
			{
				case FISH_SMALL: panic_speed = PANIC_SPEED_SMALL;
				case FISH_MEDIUM: panic_speed = PANIC_SPEED_MEDIUM;
				case FISH_BIG: panic_speed = PANIC_SPEED_BIG;
			}

			// Random direction changes
			if(random(100) < PANIC_DIRECTION_CHANGE_CHANCE)
			{
				FishDir[playerid] *= -1;
			}

			// Move within panic zone
			FishX[playerid] += FishDir[playerid] * panic_speed;

			// Keep within panic range
			new Float:panic_min = FishPanicCenter[playerid] - PANIC_RANGE;
			new Float:panic_max = FishPanicCenter[playerid] + PANIC_RANGE;

			if(FishX[playerid] > panic_max)
			{
				FishX[playerid] = panic_max;
				FishDir[playerid] = -1;
			}
			else if(FishX[playerid] < panic_min)
			{
				FishX[playerid] = panic_min;
				FishDir[playerid] = 1;
			}

			// Hard edge boundaries
			if(FishX[playerid] > EDGE_RIGHT)
			{
				FishX[playerid] = EDGE_RIGHT;
				FishDir[playerid] = -1;
			}
			else if(FishX[playerid] < EDGE_LEFT)
			{
				FishX[playerid] = EDGE_LEFT;
				FishDir[playerid] = 1;
			}

			// End panic mode
			if(FishStateCounter[playerid] <= 0)
			{
				// Decide: fake escape or real edge switch?
				new fake_escape_chance;
				switch(FishType[playerid])
				{
					case FISH_SMALL: fake_escape_chance = FAKE_ESCAPE_CHANCE_SMALL;
					case FISH_MEDIUM: fake_escape_chance = FAKE_ESCAPE_CHANCE_MEDIUM;
					case FISH_BIG: fake_escape_chance = FAKE_ESCAPE_CHANCE_BIG;
				}

				// If fake escapes remaining and random chance succeeds
				if(FishFakeEscapesRemaining[playerid] > 0 && random(100) < fake_escape_chance)
				{
					// FAKE ESCAPE - move toward center
					FishState[playerid] = FISH_STATE_FAKE_ESCAPE;
					FishFakeEscapesRemaining[playerid]--;
					
					// Set direction away from current edge
					if(FishPanicCenter[playerid] > 320.0) // at right edge
					{
						FishDir[playerid] = -1; // move left
					}
					else // at left edge
					{
						FishDir[playerid] = 1; // move right
					}
				}
				else
				{
					// REAL EDGE SWITCH - go to opposite edge
					FishState[playerid] = FISH_STATE_SEEKING_EDGE;
					FishTargetEdge[playerid] *= -1; // switch target edge
					FishDir[playerid] = FishTargetEdge[playerid];
					
					// Reset fake escape counter for next edge
					FishFakeEscapeCount[playerid] = random(FAKE_ESCAPE_COUNT_MAX - FAKE_ESCAPE_COUNT_MIN + 1) + FAKE_ESCAPE_COUNT_MIN;
					FishFakeEscapesRemaining[playerid] = FishFakeEscapeCount[playerid];
				}
			}
		}

		case FISH_STATE_FAKE_ESCAPE:
		{
			// Move slowly toward center (hesitant movement)
			new Float:fake_speed;
			switch(FishType[playerid])
			{
				case FISH_SMALL: fake_speed = FAKE_ESCAPE_SPEED_SMALL;
				case FISH_MEDIUM: fake_speed = FAKE_ESCAPE_SPEED_MEDIUM;
				case FISH_BIG: fake_speed = FAKE_ESCAPE_SPEED_BIG;
			}

			FishX[playerid] += FishDir[playerid] * fake_speed;

			// Check if reached center zone
			if(FishX[playerid] >= CENTER_MIN && FishX[playerid] <= CENTER_MAX)
			{
				// Stop and return to previous edge
				FishState[playerid] = FISH_STATE_RETURN_TO_EDGE;
				FishDir[playerid] *= -1; // reverse direction
			}

			// Safety: don't overshoot to opposite edge
			if((FishDir[playerid] == 1 && FishX[playerid] >= EDGE_RIGHT) ||
			   (FishDir[playerid] == -1 && FishX[playerid] <= EDGE_LEFT))
			{
				// Accidentally reached opposite edge, transition to panic
				if(FishDir[playerid] == 1)
				{
					FishX[playerid] = EDGE_RIGHT;
					FishPanicCenter[playerid] = PANIC_CENTER_RIGHT;
					FishTargetEdge[playerid] = 1;
				}
				else
				{
					FishX[playerid] = EDGE_LEFT;
					FishPanicCenter[playerid] = PANIC_CENTER_LEFT;
					FishTargetEdge[playerid] = -1;
				}

				FishState[playerid] = FISH_STATE_PANIC_AT_EDGE;
				switch(FishType[playerid])
				{
					case FISH_SMALL: FishStateCounter[playerid] = random(PANIC_DURATION_SMALL_MAX - PANIC_DURATION_SMALL_MIN + 1) + PANIC_DURATION_SMALL_MIN;
					case FISH_MEDIUM: FishStateCounter[playerid] = random(PANIC_DURATION_MEDIUM_MAX - PANIC_DURATION_MEDIUM_MIN + 1) + PANIC_DURATION_MEDIUM_MIN;
					case FISH_BIG: FishStateCounter[playerid] = random(PANIC_DURATION_BIG_MAX - PANIC_DURATION_BIG_MIN + 1) + PANIC_DURATION_BIG_MIN;
				}
			}
		}

		case FISH_STATE_RETURN_TO_EDGE:
		{
			// Return to the edge we just left
			new Float:return_speed;
			switch(FishType[playerid])
			{
				case FISH_SMALL: return_speed = FISH_SPEED_SMALL * 0.8;
				case FISH_MEDIUM: return_speed = FISH_SPEED_MEDIUM * 0.8;
				case FISH_BIG: return_speed = FISH_SPEED_BIG * 0.8;
			}

			FishX[playerid] += FishDir[playerid] * return_speed;

			// Check if returned to edge
			if((FishDir[playerid] == 1 && FishX[playerid] >= EDGE_RIGHT) ||
			   (FishDir[playerid] == -1 && FishX[playerid] <= EDGE_LEFT))
			{
				// Clamp to edge
				if(FishDir[playerid] == 1)
				{
					FishX[playerid] = EDGE_RIGHT;
					FishPanicCenter[playerid] = PANIC_CENTER_RIGHT;
					FishTargetEdge[playerid] = 1;
				}
				else
				{
					FishX[playerid] = EDGE_LEFT;
					FishPanicCenter[playerid] = PANIC_CENTER_LEFT;
					FishTargetEdge[playerid] = -1;
				}

				// Back to panic mode at edge
				FishState[playerid] = FISH_STATE_PANIC_AT_EDGE;
				switch(FishType[playerid])
				{
					case FISH_SMALL: FishStateCounter[playerid] = random(PANIC_DURATION_SMALL_MAX - PANIC_DURATION_SMALL_MIN + 1) + PANIC_DURATION_SMALL_MIN;
					case FISH_MEDIUM: FishStateCounter[playerid] = random(PANIC_DURATION_MEDIUM_MAX - PANIC_DURATION_MEDIUM_MIN + 1) + PANIC_DURATION_MEDIUM_MIN;
					case FISH_BIG: FishStateCounter[playerid] = random(PANIC_DURATION_BIG_MAX - PANIC_DURATION_BIG_MIN + 1) + PANIC_DURATION_BIG_MIN;
				}
			}
		}
	}

	// Update fish sprite
	PlayerTextDrawHide(playerid, fish_sprite[playerid]);
	PlayerTextDrawDestroy(playerid, fish_sprite[playerid]);

	new sprite_name[64];
	if(FishDir[playerid] == 1)
	{
		sprite_name = "conrrp_fishing:fish_right";
	}
	else
	{
		sprite_name = "conrrp_fishing:fish_left";
	}

	fish_sprite[playerid] = CreatePlayerTextDraw(playerid, FishX[playerid], 346.0, sprite_name);
	PlayerTextDrawFont(playerid, fish_sprite[playerid], 4);
	PlayerTextDrawTextSize(playerid, fish_sprite[playerid], 17.0, 17.0);
	PlayerTextDrawSetSelectable(playerid, fish_sprite[playerid], 0);

	PlayerTextDrawShow(playerid, fish_sprite[playerid]);
	
	// Play battle sounds based on fish intensity
	PlayBattleSounds(playerid);

	return 1;
}

public OnPlayerKeyStateChange(playerid, newkeys, oldkeys)
{
    // Check if player is in fishing wait state (before minigame starts)
    if(FishingWaitState[playerid])
    {
        // F key (SECONDARY_ATTACK) or ENTER key to cancel fishing
        if(PRESSED(KEY_SECONDARY_ATTACK) || PRESSED(KEY_WALK))
        {
            SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[FISHING]{FFFFFF} You cancelled fishing. Bait consumed.");
            
            // Consume bait since the cast was already made
            CallRemoteFunction("ConsumeFishingBait", "i", playerid);
            
            // Break combo
            CallRemoteFunction("BreakFishingCombo", "i", playerid);
            
            // Cancel fishing
            CancelFishing(playerid);
            
            // Save player data
            CallRemoteFunction("SavePlayerFishingData", "i", playerid);
            
            return 1;
        }
    }
    
    if(!FishingUI[playerid]) return 1;
    
    // F key (SECONDARY_ATTACK) or ENTER key to cancel fishing during minigame
    if(PRESSED(KEY_SECONDARY_ATTACK) || PRESSED(KEY_WALK))
    {
        SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[FISHING]{FFFFFF} You cancelled fishing. Bait consumed.");
        
        // Consume bait
        CallRemoteFunction("ConsumeFishingBait", "i", playerid);
        
        // Break combo
        CallRemoteFunction("BreakFishingCombo", "i", playerid);
        
        // Stop fishing session
        StopFishing(playerid);
        
        // Save player data
        CallRemoteFunction("SavePlayerFishingData", "i", playerid);
        
        return 1;
    }

    // Space key to catch fish
    if(PRESSED(KEY_JUMP))
	{
		new Float:left = CatchBoxX[playerid] - (CATCH_BOX_WIDTH / 2.0);
		new Float:right = CatchBoxX[playerid] + (CATCH_BOX_WIDTH / 2.0);
		
		if(FishX[playerid] >= left && FishX[playerid] <= right)
		{
			// SUCCESS - Player caught the fish!
			SendClientMessage(playerid, 0x2ECC71FF, "{2ECC71}[FISHING]{FFFFFF} You caught the fish!");
			
			// Play success sound before cleanup
			CallRemoteFunction("PlayCatchSuccessSoundForPlayer", "i", playerid);
			
			// Continue with normal reward process (call RPG system)
			CallRemoteFunction("OnPlayerCatchFish", "i", playerid);
			
			// Stop fishing session
			StopFishing(playerid);
		}
		else
		{
			// MISS - Player missed the catch
			PlayerFishingMissCount[playerid]++;
			
			printf("[FISHING DEBUG] Player %d missed! Miss count: %d/%d", 
				playerid, PlayerFishingMissCount[playerid], MAX_FISHING_MISSES);
			
			new string[128];
			format(string, sizeof(string), 
				"{E74C3C}[FISHING]{FFFFFF} The fish escaped! Misses: {E74C3C}%d/%d", 
				PlayerFishingMissCount[playerid], 
				MAX_FISHING_MISSES);
			SendClientMessage(playerid, -1, string);
			
			// Check if player reached max misses
			if(PlayerFishingMissCount[playerid] >= MAX_FISHING_MISSES)
			{
				// Max misses reached - fail the fishing attempt
				SendClientMessage(playerid, 0xE74C3CFF, 
					"{E74C3C}[FISHING]{FFFFFF} You failed to catch the fish! Bait consumed.");
				
				Audio_Play(playerid, "audio/conrrp_resources/fishing/fishline_snap.mp3", 0.8, 0);
				
				// Consume bait (call to RPG system if available)
				CallRemoteFunction("ConsumeFishingBait", "i", playerid);
				
				// Break combo (call to RPG system if available)
				CallRemoteFunction("BreakFishingCombo", "i", playerid);
				
				// Stop fishing session
				StopFishing(playerid);
				
				// Save player data (call to RPG system if available)
				CallRemoteFunction("SavePlayerFishingData", "i", playerid);
			}
			else
			{
				// Player still has attempts left - continue fishing
				printf("[FISHING DEBUG] Player %d still has attempts left", playerid);
				// Optionally: Make the fish move faster or change position
				// FishSpeed[playerid] += 0.5; // Increase difficulty
				Audio_Play(playerid, "audio/conrrp_resources/fishing/fishing_reel_run.mp3", 0.7, 0);
			}
		}
	}

    return 1;
}

forward PlaySwordIdle(playerid);
public PlaySwordIdle(playerid)
{
    ApplyAnimation(playerid,"SWORD","sword_idle",4.1,0,1,1,1,0,1);
	ShowFishingUI(playerid); 
	FishingUI[playerid] = true;
}

// ============================================
// FISHING WAIT STATE SYSTEM
// ============================================

// Function to calculate battle intensity based on fish state and position
stock GetBattleIntensity(playerid)
{
	// Intensity levels:
	// 1 = Low (seeking edge, calm movement)
	// 2 = Medium (fake escape, moderate movement)
	// 3 = High (panic at edge, erratic movement)
	// 4 = Very High (near edge boundaries, critical)
	
	new intensity = 1;
	
	// Check fish state
	switch(FishState[playerid])
	{
		case FISH_STATE_SEEKING_EDGE:
		{
			intensity = 1; // Low intensity
		}
		case FISH_STATE_FAKE_ESCAPE:
		{
			intensity = 2; // Medium intensity
		}
		case FISH_STATE_PANIC_AT_EDGE:
		{
			intensity = 3; // High intensity
		}
		case FISH_STATE_RETURN_TO_EDGE:
		{
			intensity = 2; // Medium intensity
		}
	}
	
	// Increase intensity if fish is near edges (critical zone)
	if(FishX[playerid] <= EDGE_LEFT + 20.0 || FishX[playerid] >= EDGE_RIGHT - 20.0)
	{
		intensity = 4; // Very high intensity near edges
	}
	
	// Increase intensity based on fish type
	if(FishType[playerid] == FISH_BIG)
	{
		intensity = (intensity >= 4) ? 4 : (intensity + 1);
	}
	
	return intensity;
}

// Function to play battle sounds periodically
stock PlayBattleSounds(playerid)
{
	new intensity = GetBattleIntensity(playerid);
	
	// Only play battle sound when intensity changes (for variation on top of looping reel sound)
	if(intensity != LastBattleIntensity[playerid])
	{
		CallRemoteFunction("PlayReelBattleSoundForPlayer", "ii", playerid, intensity);
		LastBattleIntensity[playerid] = intensity;
	}
}

// ============================================
// FISHING WAIT STATE SYSTEM
// ============================================

forward PlayFishingCastAnim(playerid);
public PlayFishingCastAnim(playerid)
{
	// Play Bat_1 animation for 500ms
	ApplyAnimation(playerid, "BASEBALL", "Bat_1", 2.0, 0, 1, 1, 1, 0, 1);
	
	// Play fishing start sound 400ms after cast animation starts
	SetTimerEx("PlayFishingStartSoundDelayed", 400, false, "i", playerid);
	
	return 1;
}

forward PlayFishingStartSoundDelayed(playerid);
public PlayFishingStartSoundDelayed(playerid)
{
	// Play fishing start sound (casting sound)
	CallRemoteFunction("PlayFishingStartSoundForPlayer", "i", playerid);
	return 1;
}

forward StartFishingWait(playerid);
public StartFishingWait(playerid)
{
	// Play sword_idle animation
	ApplyAnimation(playerid, "SWORD", "sword_idle", 4.1, 0, 1, 1, 1, 0, 1);
	
	// Clear fishing starting flag and set wait state
	FishingStarting[playerid] = false;
	FishingWaitState[playerid] = true;
	FishingWaitStartTime[playerid] = GetTickCount();
	PlayerFishingMissCount[playerid] = 0; // Reset miss counter
	
	// Disable checkpoint during fishing to prevent performance issues
	DisablePlayerCheckpoint(playerid);
	
	// Get fishing level from RPG system
	new fishingLevel = CallRemoteFunction("GetPlayerFishingLevel", "i", playerid);
	if(fishingLevel < 1) fishingLevel = 1;
	if(fishingLevel > 100) fishingLevel = 100;
	
	// Get equipment bonuses from RPG system
	new biteSpeedBonus = CallRemoteFunction("GetPlayerBiteSpeedBonus", "i", playerid);
	
	// Calculate base wait time based on level
	// Level 1: 15 seconds, Level 100: 3 seconds
	// Formula: 15000 - (level * 120) = progressive reduction
	new baseWaitTime = 15000 - (fishingLevel * 120);
	if(baseWaitTime < 3000) baseWaitTime = 3000; // Minimum 3 seconds
	
	// Apply equipment bonus (bite speed bonus reduces wait time)
	// Each 1% bonus = 1% faster (shorter wait)
	new Float:bonusMultiplier = 1.0 - (float(biteSpeedBonus) / 100.0);
	if(bonusMultiplier < 0.5) bonusMultiplier = 0.5; // Max 50% reduction
	
	new waitTime = floatround(float(baseWaitTime) * bonusMultiplier);
	
	// Add random variance (±20%)
	new variance = waitTime / 5;
	waitTime = waitTime - variance + random(variance * 2);
	
	// Store when the fish will bite
	FishingBiteTime[playerid] = FishingWaitStartTime[playerid] + waitTime;
	
	// Start checking for bite
	FishingWaitTimer[playerid] = SetTimerEx("CheckFishingBite", WAIT_CHECK_INTERVAL, true, "i", playerid);
	
	SendClientMessage(playerid, 0x3498DBFF, "{3498DB}[FISHING]{FFFFFF} Waiting for a fish to bite...");
	// Debug message
	new string[128];
	format(string, sizeof(string), "{3498DB}[DEBUG]{FFFFFF} Fishing Level: %d | Wait Time: %.1f seconds", 
		fishingLevel, float(waitTime) / 1000.0);
	SendClientMessage(playerid, -1, string);
}

forward CheckFishingBite(playerid);
public CheckFishingBite(playerid)
{
	if(!FishingWaitState[playerid])
	{
		KillTimer(FishingWaitTimer[playerid]);
		FishingWaitTimer[playerid] = 0;
		return;
	}
	
	new currentTime = GetTickCount();
	
	// Check if it's time for the fish to bite
	if(currentTime >= FishingBiteTime[playerid])
	{
		// Fish has bitten!
		OnFishBite(playerid);
		
		// Stop wait state
		KillTimer(FishingWaitTimer[playerid]);
		FishingWaitTimer[playerid] = 0;
		FishingWaitState[playerid] = false;
	}
	else
	{
		// Optional: Show waiting indicator
		new timeLeft = (FishingBiteTime[playerid] - currentTime) / 1000;
		
		// You can add visual feedback here (e.g., textdraw updates)
		// For now, just a periodic message every 3 seconds
		if(timeLeft % 3 == 0 && timeLeft > 0)
		{
			new string[64];
			format(string, sizeof(string), "~y~Waiting... ~w~%d~y~s", timeLeft);
			GameTextForPlayer(playerid, string, 1000, 3);
		}
	}
}

forward OnFishBite(playerid);
public OnFishBite(playerid)
{
	ApplyAnimation(playerid, "SWORD", "sword_block", 4.1, 1, 1, 1, 1, 0, 1);

	// Fish has bitten the bait!
	SendClientMessage(playerid, 0x2ECC71FF, "{2ECC71}[FISHING]{FFFFFF} A fish is biting! Start the minigame!");
	GameTextForPlayer(playerid, "~g~FISH ON!", 2000, 3);

	// Play fishing strike sound for the minigame
	CallRemoteFunction("PlayFishingStrikeSoundForPlayer", "i", playerid);
	
	// Play fishing theme music during minigame (looping)
	CallRemoteFunction("StartFishingMusicForPlayer", "i", playerid);

	// Play fishing reel sound for the minigame
	CallRemoteFunction("PlayFishingReelSoundForPlayer", "i", playerid);
	
	// Generate fish data (call RPG system with zone TYPE, not zone ID)
	// GetPlayerZone returns 1-based zone index (1, 2, 3...), 0 means no zone
	new zoneIdx = CallRemoteFunction("GetPlayerZone", "i", playerid);
	new zoneType = -1; // Default to invalid
	if(zoneIdx > 0)
	{
		// Convert 1-based index to 0-based for GetZoneTypeFromIndex
		zoneType = CallRemoteFunction("GetZoneTypeFromIndex", "i", zoneIdx - 1);
	}
	CallRemoteFunction("GenerateFish", "ii", playerid, zoneType);
	
	// Start the fishing minigame
	ShowFishingUI(playerid);
	FishingUI[playerid] = true;
}

// Function to load fishing level from database (call this when player logs in)
stock LoadPlayerFishingLevel(playerid)
{
	// This should be called from your main gamemode when loading player data
	// Example MySQL query:
	// mysql_format(handle, query, sizeof(query), "SELECT fishingskill FROM players WHERE id = %d", PlayerData[playerid][pID]);
	// mysql_tquery(handle, query, "OnLoadFishingLevel", "i", playerid);
	
	// For now, set a default value
	PlayerFishingLevel[playerid] = 1;
}

// Callback for loading fishing level from database
forward OnLoadFishingLevel(playerid);
public OnLoadFishingLevel(playerid)
{
	// Example implementation:
	// new rows;
	// cache_get_row_count(rows);
	// if(rows)
	// {
	//     cache_get_value_name_int(0, "fishingskill", PlayerFishingLevel[playerid]);
	// }
	
	// For testing, you can use /setfishlevel command
}

// Function to update fishing level in database
stock UpdatePlayerFishingLevel(playerid, newLevel)
{
	PlayerFishingLevel[playerid] = newLevel;
	
	// Example MySQL query:
	// mysql_format(handle, query, sizeof(query), "UPDATE players SET fishingskill = %d WHERE id = %d", 
	//     newLevel, PlayerData[playerid][pID]);
	// mysql_tquery(handle, query);
}

// Function to cancel fishing
stock CancelFishing(playerid)
{
	if(FishingWaitState[playerid])
	{
		KillTimer(FishingWaitTimer[playerid]);
		FishingWaitTimer[playerid] = 0;
		FishingWaitState[playerid] = false;
		FishingStarting[playerid] = false;
		
		ClearAnimations(playerid);
		if(IsPlayerAttachedObjectSlotUsed(playerid, 0))
		{
			RemovePlayerAttachedObject(playerid, 0);
		}
		
		// Re-enable checkpoint after canceling fishing
		// The CheckBoatCheckpoints timer will restore boat checkpoint if needed
		
		SendClientMessage(playerid, 0xE74C3CFF, "{E74C3C}[FISHING]{FFFFFF} You stopped fishing.");
	}
}

// Function to stop fishing (called after catch or fail)
stock StopFishing(playerid)
{
	// Hide fishing UI
	HideFishingUI(playerid);
	
	// Reset fishing state
	FishingUI[playerid] = false;
	FishingStarting[playerid] = false;
	PlayerFishingMissCount[playerid] = 0;
	
	// Reset fishing state in RPG system
	CallRemoteFunction("SetPlayerFishingState", "ii", playerid, 0);
	
	// Stop all fishing sounds (reel sound, music, etc.)
	CallRemoteFunction("CleanupPlayerAudioForPlayer", "i", playerid);
	
	// Stop fish movement timer
	if(FishTimer[playerid] != 0)
	{
		KillTimer(FishTimer[playerid]);
		FishTimer[playerid] = 0;
	}
	
	// Clear animations
	ClearAnimations(playerid);
	
	// Remove fishing rod attachment if exists
	if(IsPlayerAttachedObjectSlotUsed(playerid, 0))
	{
		RemovePlayerAttachedObject(playerid, 0);
	}
	
	// Restore player control
	TogglePlayerControllable(playerid, true);
	
	// Re-enable checkpoint after fishing ends (boat checkpoint system will restore it if needed)
	// Note: The CheckBoatCheckpoints timer in fishing_rpg_master.pwn will automatically
	// restore the boat checkpoint if player is still on a fishing boat
}

// Public function that can be called from gamemode
forward SetPlayerFishingLevel(playerid, level);
public SetPlayerFishingLevel(playerid, level)
{
	if(level < 1) level = 1;
	if(level > 10) level = 10;
	
	PlayerFishingLevel[playerid] = level;
	return 1;
}

// Public function to get fishing level (callable from gamemode)
forward GetPlayerFishingLevel(playerid);
public GetPlayerFishingLevel(playerid)
{
	// Get level from RPG system
	return CallRemoteFunction("GetPlayerFishingLevelRPG", "i", playerid);
}

// Public function to check if player is in fishing wait state (callable from fishing_rpg_master)
forward IsPlayerInFishingWaitState(playerid);
public IsPlayerInFishingWaitState(playerid)
{
	return FishingWaitState[playerid] ? 1 : 0;
}

// Public function to check if player is fishing
forward IsPlayerFishing(playerid);
public IsPlayerFishing(playerid)
{
	return FishingStarting[playerid] || FishingWaitState[playerid] || FishingUI[playerid];
}